import { TIMING_CONSTANTS } from "./timings";

export const RATE_LIMIT_CONFIG = {
    GENERAL: { requests: 100, window: TIMING_CONSTANTS.FIFTEEN_MINUTES },
    AUTH: { requests: 5, window: TIMING_CONSTANTS.FIFTEEN_MINUTES },
    PASSWORD_RESET: { requests: 3, window: TIMING_CONSTANTS.ONE_HOUR },
    EMAIL_VERIFICATION: { requests: 3, window: TIMING_CONSTANTS.FIVE_MINUTES },
    REFRESH_TOKEN: { requests: 20, window: TIMING_CONSTANTS.FIFTEEN_MINUTES },
    HEALTH_CHECK: { requests: 60, window: TIMING_CONSTANTS.FIFTEEN_MINUTES },
    ROUTE_SCANNING: { requests: 5, window: TIMING_CONSTANTS.ONE_HOUR },
    PROGRESSIVE_DELAY: { threshold: 5, delayMs: 500, maxDelayMs: 5000 },
    SCAN_LOG_LIMIT: 3,
    GLOBAL_LOGIN_ALERT_THRESHOLD: 20,
    GLOBAL_LOGIN_ALERT_WINDOW_SECONDS: 24 * 60 * 60,
};
